import pandas as pd
from os.path import join

configfile: 'config/config.yml'

#load participants.tsv file, and strip off sub- from participant_id column
df = pd.read_table(config['participants_tsv'])
subjects = df.participant_id.to_list() 
subjects = [ s.strip('sub-') for s in subjects ]



#get list of ROIs
df_targets = pd.read_table(config['targets_dseg_tsv'])
targets = df_targets.name.to_list()



#get seeds, as keys in template_prob_seg
seeds = config['template_prob_seg'].keys()


#bids-naming for subject and template (only alphanumeric characters)
wildcard_constraints:
    subject="[a-zA-Z0-9]+",
    template="[a-zA-Z0-9]+",
    seed="[a-zA-Z0-9]+",
    k="[0-9]+",


template=config['template']


include: 'rules/common.smk'

rule all_diffparc:
    input:
      group_tractseg = expand(bids(root='results/tractmap',template='{template}',label='{seed}',method='spectralcosine',k='{k}',desc='avgtractmap',suffix='dseg.nii.gz'),template=config['template'],seed=seeds,k=range(2,config['max_k']+1))

include: 'rules/hcp_mmp.smk'
include: 'rules/diffparc.smk'
include: 'rules/tractmap.smk'
