import pandas as pd
from os.path import join

configfile: 'config/config.yml'

#load participants.tsv file, and strip off sub- from participant_id column
df = pd.read_table(config['participants_tsv'])
subjects = df.participant_id.to_list() 
subjects = [ s.strip('sub-') for s in subjects ]



#get list of ROIs
f = open(config['targets_txt'],'r')
targets = [line.strip() for line in f.readlines()]
f.close()

#get seeds, as keys in template_prob_seg
seeds = config['template_prob_seg'].keys()


#bids-naming for subject and template (only alphanumeric characters)
wildcard_constraints:
    subject="[a-zA-Z0-9]+",
    template="[a-zA-Z0-9]+",
    seed="[a-zA-Z0-9]+"



## -----  below is diffparc pipeline ----
# requires:
#   template-space seed:  'results/template/seed_{template}_{seed}.nii.gz'
#   ants warps
#        -> from ants_build_template
#   subject-space targets:  'results/diffparc/sub-{subject}/masks/lh_rh.native.hcp-mmp.nii.gz'
#        -> hcp_mmp_native subworkflow
#   pre-processed dwi & bedpost
#        -> from prepdwi or hcp 
#        -> have user define input path in config file



rule all:
    input: expand('results/clustering/group_space-{template}_seed-{seed}_method-spectralcosine_k-{k}_cluslabels.nii.gz',template=config['template'],seed=seeds,k=range(2,config['max_k']+1))

subworkflow hcp_mmp_to_native:
    workdir: '../subworkflows/hcp_mmp_to_native'
    snakefile: '../subworkflows/hcp_mmp_to_native/workflow/Snakefile'
    configfile: 'config/config_hcp_mmp_to_native.yml'


include: 'rules/diffparc.smk'
